@startmindmap

title Biz Overview

*[#lightgreen] Biz
++ Options
+++ SaaS
++++ MVP to start, test the market
++++ Lots of bugs, LOTS
+++ Retail
+++ Affiliate Marketing
+++ Website + Advertising
-- Required Knowledge
--- Marketing
--- Sales
--- Copywriting
++ Competition
+++ None
++++ Easier because of lower expectations
+++ Lots
++++ You must be significantly better
++++ Consumers stick with trusted brands

@endmindmap
