@startmindmap
title Influence: Overview

legend left
  <&key> Key
  Light Green   \t: Start.
  Light Blue    \t: Has notes/template with the same name.
  Yellow        \t: Has an image with the same name.
  Light Red     \t: Notable nodes.
endlegend


*[#lightgreen] Overview

**[#F88] Reciprocation
*** Reciprocal concession
**** Leverage the contrast principle
***** Large offer first, smaller offer second
**** Users feel more satisfied
***** Control/freedom over concession
**** Choose what's reciprocated

**[#F88] Commitment and consistency
*** Foot-in-the-door technique
**** Get a small initial commitment
***** Admission / purchase / anything
***** Incentivise if needed
**** Incrementally grow commitments
***** Leverages consistency
*** Commitment
**** Must be an internal choice
***** Incentivise
****** Smaller is better
***** Eventually remove inducements
**** Public
***** Enforces consistency
***** Written
****** Powerful
****** Serves as social proof
****** Serves as a reminder
**** Written
***** Changes self image
*** Consistency
**** People tend to be consistent with prior commitments
**** The leverage

**[#F88] Social proof
*** The more the better
*** Groups
**** Leverage diffusion of responsibility
****[#F88] Pluralistic ignorance
**** Maximise/optimise conditions
***** Group endorsement
****** Peer pressure
***[#F88] Uncertainty
**** People look to others
*****[#F88] Pluralistic ignorance
****** Key leverage
**** Leverage
***[#F88] Similarity
**** People are influenced by similar demographics
*** Demonstrate social proof
**** Examples
***** Photos
****** People purchasing
***** Public testimonies
***** Group endorsement
****** Induce conformity
****** Live chat / testimonies

left side

**[#F88] Liking
*** Avoid schisms
**** Causes
***** Group boundaries
****** Competing groups
**** Use cross group cooperation
*** Tactics
****[#F88] Physical attractiveness
***** Not driven by sex
****** Works with same sex heterosexuals
****[#F88] Compliments
***** Flattery
***** Can be in abundance
***** Can be exaggerated
***** Can be transparent
****** Obvious ploys
****[#F88] Similarity
***** Demographics / clothing / agendas / body language etc.
****[#F88] Familiarity
***** Frequent contact
***** Ideas / people / concepts etc.
****[#F88] Association
***** Positive things
****** Can be unrelated
****** The luncheon technique
****** Used to restore image
******* Most effective with recent negative experience
***** Unconscious
***** People use it to feel superior
 
**[#F88] Authority
*** Symbols
**** Titles
**** Clothing
**** Trappings
**** Size
**** Significance
*****_ e.g. absolute value

**[#F88] Scarcity
***[#F88] Competition
**** High demand
***** Use social proof
***** Optimal condition for scarcity
***** Very effective
**** Limited supply
***[#F88] Reactance
**** A reaction to loss/limitation of freedom
***[#F88] Exclusivity
**** Information
***** Significantly more valuable
*** Tactics
**** Loss leader
**** Deadline
**** Limited number
***** Bait

@endmindmap
