@startmindmap

title Influence: 1. Weapons of Influence

legend left
  <&key> Key
  Light Green   \t: Start.
  Light Blue    \t: Has notes/template with the same name.
  Yellow        \t: Has an image with the same name.
  Light Red     \t: Notable nodes.
endlegend


*[#lightgreen] Weapons of influence
** Fixed-action patterns
*** Automatic
*** Same fashion and order
**** Like a tape recorder
*****_ e.g. courtship
***[#F88] Trigger feature
****_ e.g defence mechanism
**** Colour / shape / anything
*****_ e.g. some defining characteristic of a predator or mate
**** Humans have them too
***** Requests with reasons
****** [question] because [reason]
***** Stereotype
****** Expensive items sell better
******* A shortcut to quality evaluation
***** Coupons that don't save money
****** The assumption is that they do

** The contrast principle
*** Present expensive items first
*** Present cheap products second
**** Seems cheaper by contrast

@endmindmap
