@startmindmap

title Influence: 4. Social Proof

legend left
  <&key> Key
  Light Green   \t: Start.
  Light Blue    \t: Has notes/template with the same name.
  Yellow        \t: Has an image with the same name.
  Light Red     \t: Notable nodes.
endlegend


*[#lightgreen] Social Proof
** Motivators
***[#F88] Uncertainty
**** Subjects look to group members
****[#F88] Pluralistic ignorance
***** Conform to the group
****** Diffusion of responsibility
***[#F88] Similarity
**** Copycats
***** Suicides
***** Homicides
**** Demographics
**** Behavioural attributes

** Examples
*** The bystander effect
*** Testimonies
*** Sales pitch / marketing

left side

** Characteristics
*** Conformity
**** Pluralistic ignorance
***** More effective with strangers
*** Can be subtle
****:Sometimes you may follow something that is
set by the majority without realising it;
*** Demonstrations
**** Paid actors
***** Consumers from Mars
**** Testimonies

 
@endmindmap
