@startmindmap

title Influence: 5. Liking

legend left
  <&key> Key
  Light Green   \t: Start.
  Light Blue    \t: Has notes/template with the same name.
  Yellow        \t: Has an image with the same name.
  Light Purple  \t: A layer of the PMF Pyramid.
  Light Red     \t: Notable nodes.
endlegend


*[#lightgreen] Liking

** Physical attractiveness
*** Unconscious
**** Most deny that they are affected
*** Not influenced by sex
**** Same gender influences

** Similarities
*** Examples
**** Demographics
**** Clothing
**** Agendas
**** Background
**** Mirror body language

** Compliments / flattery
*** Can be
**** Abundant
**** Transparent (apparently motivated)
**** Inaccurate/exaggerated 
*** Very effective

left side

** Familiarity
*** Built through contact
**** Influences
***** Significantly
****** Decision making
****** Persuasiveness
*** Schisms
**** Remedied by cross group cooperation
***** Common values
***** Common, legitimate goals
***** It increases...
****** general happiness
****** general satisfaction
*** Examples
**** Friendships
**** Prior experience
*****_ e.g. faces you've seen before

** Association
*** Generally an unconscious behaviour
*** Positive
**** Examples
***** Celebrities
****** People raising their public image
****** Brands
***** Athletes
****** Brands
***** Government policies
****** Politicians
***** A good meal
****** The luncheon technique
**** Builds positive image
***** People gravitate towards this
**** Doesn't influence future positive associations
**** People must feel superior to competition
***** Tribalism
*** Negative
**** Influences future positive associations
**** Builds negative image
***** People avoid this

@endmindmap
