@startmindmap
title Influence: 7. Scarcity

legend left
  <&key> Key
  Light Green   \t: Start.
  Light Blue    \t: Has notes/template with the same name.
  Yellow        \t: Has an image with the same name.
  Light Red     \t: Notable nodes.
endlegend


*[#lightgreen] Scarcity

** Principles
*** Prevent thinking or pondering
**** Time limit
***** It will be gone soon
**** They can't have it later
**** Competition
***** It might be gone soon
**** Induce reactance through potential loss
*** Induce reactance
**** Take a deal off the table

** Competition
*** Create competition
****[#F88] Social proof of demand
***** Optimal condition for scarcity
**** A physical presence of competition, a person
**** Fear of loss
***** Causes sales pressure
*** Effects
**** Increased perceived value

left side

** Reactance
*** Response to losing freedoms
**** People like autonomy
**** Freedom of choice
*** The cause of the scarcity principle
*** Effects
**** Increased perceived value
**** A tendency to want what they can't have
**** Alignment with censored ideas

** Tactics
*** Limited number
*** Deadline
**** Limited time
*** Depleting supply
**** E.g. selling fast / popular demand
*****  Social proof makes this powerful

** Exclusivity
*** Information
**** Extremely effective
**** E.g. Exclusively telling someone that "there will be a shortage of..."

** Bait
*** The loss leader tactic
**** Sell a leading product at a loss
**** Generate interest in other products

@endmindmap
