@startmindmap

title Influence: 2. Reciprocation

legend left
  <&key> Key
  Light Green   \t: Start.
  Light Blue    \t: Has notes/template with the same name.
  Yellow        \t: Has an image with the same name.
  Light Purple  \t: A layer of the PMF Pyramid.
  Light Red     \t: Notable nodes.
endlegend


*[#lightgreen] Reciprocation
** Works for solicited / unsolicited initiations
** Can choose the return favour -- just ask
** How much the initiator is liked has little effect on the outcome

left side

** Reciprocal concession
*** Reject-then-retreat technique
*** Attributes
**** Large initial demand/offer
**** A second more reasonable offer
*** Works because
**** Responsibility
***** The subject feels they have control over the concession
**** Satisfaction
***** The subjects generally report higher degree of satisfaction


@endmindmap
