@startmindmap

title Influence: 3. Reciprocation

legend left
  <&key> Key
  Light Green   \t: Start.
  Light Blue    \t: Has notes/template with the same name.
  Yellow        \t: Has an image with the same name.
  Light Red     \t: Notable nodes.
endlegend


*[#lightgreen] Commitment and Consistency
** Commitment
*** Foot-in-the-door technique
*** Initial commitment
**** Can be small
**** Can be unrelated
*** Motivators
**** Inducements
***** Until self-supporting beliefs take over
**** Publicity
**** Written
**** Self image
**** Inconvenient truths
***** "Walls of inconsistency"
**** Inner choice
*** Effects
**** Changes self image
** Methods
*** Lowball technique
**** Promise a deal (publicity; discount) then revoke
*** Essay competitions
*** Public statements
*** Written statements

left side

** Consistency
*** Perceptions
**** Intellectual strength
**** Truthful
**** Logical
**** Rational
*** Effects
**** People tend to be consistent
***** Public declarations etc.
*** Reason
**** Affords a reduction in cognitive load
** Inconsistency
*** Perceptions
**** Scatter brained
**** Deceitful
**** Illogical
**** Unstable
**** Unreliable

@endmindmap
