@startmindmap
title Influence: 6. Authority

legend left
  <&key> Key
  Light Green   \t: Start.
  Light Blue    \t: Has notes/template with the same name.
  Yellow        \t: Has an image with the same name.
  Light Red     \t: Notable nodes.
endlegend


*[#lightgreen] Authority
** Project authority
***[#F88] Size
***[#F88] Titles
**** M.D.
**** Professor
***[#F88] Clothing
**** Uniform
**** Business suit
**** Lab coat
***[#F88] Significance
**** The greater the significance, the larger it seems
***** Numbers
***** Symbolic
***[#F88] Trappings
**** Clothing
**** Jewellery
**** Vehicles

left side

** Examples
*** Schools
*** Parents
*** Government
*** Guards
*** Business man

** Obedience
*** Causes
**** Cognitive shortcut
**** Consequences
**** Conditioning
*** Given without thought or questioning
**** Even professionals

** People underestimate its impact
*** Particularly males

** Defence
*** Question
****[#F88] Credentials
****[#F88] Integrity
***** Signs of manipulation
****** Rhetorical concessions
******* Concede on secondary points
****** Dishonest "impartial" messages

@endmindmap
