@startmindmap

legend left
  <&key> Key
  Light Green   \t: Start.
  Light Blue    \t: Has notes/template with the same name.
  Yellow        \t: Has an image with the same name.
  Light Purple  \t: A layer of the PMF Pyramid.
  Light Red     \t: Notable nodes.
endlegend

title Lean Product Process: Apply the Principles of Great UX Design

*[#lightgreen] UX Design
** Great UX
*** Usability
**** User profile
***** Physical ability
***** Domain knowledge
***** Personas
**** Efficiency
***** Number of steps taken to figure out a task
****** Clicks, taps, keystrokes, actions..
***** Learnability
****** Onboarding
******* Tutorials
****** Important
******* Quickly affects decisions
****** Measure zero to hero
***** Time taken
***** Cognitive load
***** Avoid taxing effort
****** High effort less users
****** Mental
****** Physical
****** Memory
**** Testing
***** Collect data
***** % users able to complete task
****** % users that had problems
**** Focus
***** User goals
***** User tasks
**** Easy
**** Effortless
**** A state of "Flow"
***** Immersion

*** Delight
**** Emotions
***** Enjoyable to use?
**** Aesthetics
***** Enjoyability
***** High quality
***** Great first impression
**** Simplicity
***** Minimal
***** Enjoyment
**** Pre-emptive
***** Smart defaults
***** Answering top-of-mind questions
***** Makes it relatable
**** Personality
***** Tone
***** Humour
**** Dynamic responses
*****:Rubber band scrolling at
the end of a scrolling screen;
***** Satisfying feedback
******_ e.g. cash register
**** Surprise
***** Funny 404 pages

left side

' === UX DESIGN ICEBERG === '
**[#yellow] UX Design Iceberg
*** Conceptual design
****[#yellow] PMF Pyramid
***** Sits just above feature set layer
******_ the whole iceberg is the UX layer
**** Core concept
***** Forms the essence of the experience
***** Resonates with target audience
***** Intuitive to use
***** Possible design metaphor
****** Can be multi-centric
**** Often contributes to innovation
**** User research
***** Other observers
****** Team debriefs
****** Product team members
******* First hand
****** Key takeaways
***** Discovery
****** Interviews
****** Usability tests
****** Surveys
***** Specialised field in UX
***** Deeply understand
******_ for core concept
***** Personas
****** Additions for UX
******* Technical abilities
******** Low: means simple UI
******** High: means more powerful tools
******* Context
******** Rushed for time
******** Laid back

*** Information architecture
**** Focus
***** Feature set
**** Techniques
***** Card sorting
****** Defines logical groups for UI elements
****** Ask user to do the sorting
****** Observe
****** User verbalises
**** Test
***** Findability
****** Measure
******* Time taken
******* Success / failures
****** Analytics
******* Paths taken
**** Defines how to organise site information
**** Sitemap
***** Test
****** Labels
*******_ their intended meaning
***** Deliverable
****** Navigation
******_ for any software product

' === INTERACTION DESIGN === '
*** Interaction design
**** Conceptual design
***** Important to interaction design
**** Concerned with
***** State
****** Product availability
*******_ allows a particular flow through your app
****** Modes
*******_ like edit mode
******* Tutorials
******** Tutorial mode
******** Normal mode
******* Help
******** Easy mode
********* Guided by questions
******** Hard mode
********* Hands off
***** Input
***** Feedback
****** Error messages
****** Response time
******* Confirmation
******** Animated spinners
******** Loading bar for long tasks
***** Navigation
****** Flow
******* Complicated?
******** Wizard
***** Any form of interactivity
**** How the user and the product interact
***** Clicks
***** Typing
***** Navigation
****** Governed by information architecture
**** Flowcharts
***** Express complex flows
**** Wireframes
***** Often preferred to flowcharts
***** You can annotate error states
***** Not pixel perfect
***** Focus questions on
****** Layout
****** UX
****** Interaction
***** Apply divergent thinking
******_ like brainstorming
****** Even the bad ideas
******* Narrowing too early is bad
***** Solution space artifact
****** Testable

' === VISUAL DESIGN === '
*** Visual design
****[#yellow] UX Design Iceberg
***** Tip / top
****** Immediately obvious to customers
**** Aka Graphic design / look and feel / chrome

**** Effects
***** Reinforced visual hierarchy
***** Brand personality
***** Delight
***** Differentiation from competitors

**** Colour
***** Palette
****** Use different saturations
****** Use an accent colour
***** Make some elements stand out
***** Emotion
****** Interpretation can vary around the world
******* Consider the audience
****** Warm
*******[#red] Red
******** Aggression / passion / power / danger
*******[#orange] Orange
******** Energetic / vibrant
*******[#yellow] Yellow
******** Happiness / sunshine
******** Energising / passionate
****** Subdued
*******[#green] Green
******** Nature / growth / money
*******[#blue] Blue
******** Trustworthiness / calm
*******[#purple] Purple
******** Luxury / creativity
******* Calming / reserved
******[#black] Black
******* Sophistication / elegance / mystery
******[#brown] Brown
******* Warmth / earth
******[#white] White
******* Purity / cleanliness / simplicity

**** Typography
***** Used to convey visual hierarchy
***** Limit the number of fonts you use
***** Approach
****** Pick one font for large text
****** Pick one font for body text
****** Pick only a few text sizes
******* Be consistent throughout the app
***** Conveyed attributes
****** Formal / Informal
****** Classic / modern
****** Light / dramatic
***** Sans serif
****** Lower resolution
****** Better for web
***** Serif
****** Higher resolution
****** Harder to read when smaller
****** Better for print

**** Graphics
***** Types
****** Images
****** Illustrations
****** Lines
****** Textures
****** Gradients
****** Shadows
****** Icons
******* Iconography
******** Used in marketing
******** Good for small screen size
******** Meaning
********* Standard symbols
***** Critical for ecommerce
****** Hugely increase conversion rate
***** Hero images
****** Common
****** Convey product / message
**** Style guide
**** Layout grid
**** Mockups

' === DESIGN PRINCIPLES === '
** Design Principles
*** Gestalt principles
*** Visual hierarchy
*** Principles of composition
*** Responsive design
*** Designing for multiple screen sizes

' === MISC === '
** Misc
*** Copy
**** Part of UX design
*** User opinions matter

@endmindmap
