@startmindmap

title Emerging Industries 2020

*[#lightgreen] Emerging industries

** Green
** AI

left side

' === eCommerce === '
** eCommerce
*** Continues to grow
***: Businesses moving from
traditional stores;

@endmindmap
