@startmindmap

title Market Research - Competitors


*[#lightgreen] Competitors

' PRODUCTS '
** Products
*** Pricing
*** Tiers
*** Differentiation?
**** Outranking
**** Better quality
**** Be authentic / transparent
**** Lack of competition with paid advertising?

** Computing platform

' TRAFFIC '
** Traffic
*** Potential revenue per visitor
*** Engagement

** Value

' REVENUE '
** Revenue
*** Sources of income

' MARKETING '
** Marketing
*** Social media
**** Shares, likes..
**** Mailing list
**** Blogs
**** Advertising
***** SEMRush
***** Google, Facebook etc..
***** Affiliate programs
***** Referral program
******_ homepage footer

' SEO '
** SEO
*** Good or bad
*** SEMRush, AHRefs
****_ tools to analyse
*** Ranking
**** Possible?

left side

** A plan to win

** Engage

' INCENTIVES '
*** Offer incentives
**** Amazon giftcard
****_ ~70% response rate

*** most won't respond
*** Employees, owners
*** Cold email, Linkedin
*** Template

' REFERRALS '
*** Get referrals
****_ on positive rapport

' FEEDBACK '
*** Feedback on ideas
**** Iterate

' APPROACH '
*** Be concise, interesting, brief, and show gratitude
**** 3-4 sentences
**** Your mission in one sentence

** Total competition
*** Too much?
**** Too hard to compete
*** None?
**** Possibly can't be monetised
*** Not too much?
**** Good

@endmindmap
