@startmindmap

title Market Research

*[#lightgreen] Market Research

' PLAN '
** Create a strategy
*** Have alternative tactics

' CUSTOMER '
** Customer

*** Determine target demographics
**** Will move (purchase) fast
**** Will pay premium
*** Engage
**** Use a framework
**** Extract ideas
**** Iterate
**** Their perspective
***** Needs
***** Wants
***** Problems
****** Existing solutions
******* Shortcomings
******* Determine competitors
*** Model
**** Problems
**** Will they pay
**** Likes / dislikes
**** Currently uses X solution
*** Choose the biggest problem


' SOCIAL '
*** Social Ratings
**** Develop a format
*****_ for modelling
**** Twitter, Reddit, YouTube, Facebook, Quora, forums
**** Opinions
**** Questions
**** Problems
**** Likes / Dislikes
**** SEO
***** Pain-point keywords
******_ deeper understanding

left side

' NICHE '
** Market
*** Large market
**** Identify
***** Poised for change / growth
***** ~$1Bn: Allows errors, high margins
*** Niche
**** Evaluate
***** Has demand
***** Multiple revenue channels
***** Find another if it doesn't suit all your needs
****_ is a small corner

**** Identify
***** Approaches
****** Customer first
*******[#lightblue]: Amazon's approach to
product development;
****** List of interests
******* Things you do
******** Model yourself
******* Determine problems

' SEO '
** SEO
*** Determine Keywords
**** Google Trends, Google Adwords

' COMPETITORS '
** Competitors
***_ see competitors mindmap

' TEST '
** Landing page
*** Test market engagement
*** Pre sales
*** Drive traffic with ads
*** Mailing list
**** Track engagement
**** News letter
*** Test
**** Samples / prototype
**** A/B split testing
***** Optimise conversions
***** Iterate
***** Feedback

' PARTNERING '
** Partner 
***_ optional / possibility
***_ while you build out your own

@endmindmap
