@startmindmap

title Biz Overview

*[#lightgreen] Biz

** Resources
*** Playbook
**** Stategies / tactics

' OPTIONS '
** Options
*** SaaS
**** MVP to start, test the market
**** Lots of bugs, LOTS
*** Retail
*** Affiliate Marketing
*** Website + Advertising

' COMPETITION '
** Competition
*** None
**** Easier because of lower expectations
*** Lots
**** You must be significantly better
**** Consumers stick with trusted brands

' BUSINESS MODEL '
** Business model

left side

' REQUIRED KNOWLEDGE '
** Required Knowledge
*** Marketing
*** Sales
*** Copywriting

' GETTING STARTED '
** Getting started
*** Business plan
****[#lightblue] Sequoiacap's template
***[#lightblue] Defmarco's startup checklist
*** Determine Niches
****_ see market research map
*** Product development
****[#lightblue]: Amazon's approach to
product development;
***** Customer first approach

** Market research
***_ see market research map

@endmindmap
